gpu: 0
sample_rate: 16000
# sample_rate: 44100

ar_model: 'TPekarekRosin/uhh_ub_cv_ar_small_ds' # 'ar_s5217_be_CEclassification_e4_lr3e-5.pth'
num_classification_layers: 1
num_classifier_attention_heads: 4
n_mfcc: 24
win_length: 400
hop_length: 160
fc_hidden_dim: 512
fc_output_dim: 256
num_classes: 9

model_name: "small.en"
frame_duration: 30 # 10, 20 or 30 for vad
n_channels: 1